/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './app/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './lib/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'gray-50': '#FCFCFC',
        'gray-100': '#F5F7F9',
        'gray-200': '#F0F0F0',
        'gray-300': '#D9D9D9',
        'gray-400': '#BFBFBF',
        'gray-500': '#8C8C8C',
        'gray-600': '#595959',
        'gray-700': '#454545',
        'gray-800': '#262626',
        'gray-900': '#1F1F1F',
        'gray-950': '#141414',
        'brand-50': '#F3F4FC',
        'brand-100': '#E7EAF9',
        'brand-200': '#C2D1F0',
        'brand-300': '#99B4E6',
        'brand-400': '#437ED4',
        'brand-500': '#0052CD',
        'brand-600': '#004AC2',
        'brand-700': '#0040B6',
        'brand-800': '#0035AB',
        'brand-900': '#002398',
        'brand-950': '#001766',
        'green-50': '#F0FDF5',
        'green-100': '#DCFCE8',
        'green-200': '#BBF7D1',
        'green-300': '#86EFAD',
        'green-400': '#4ADE81',
        'green-500': '#22C55E',
        'green-600': '#16A34A',
        'green-700': '#15803C',
        'green-800': '#166533',
        'green-900': '#14532B',
        'green-950': '#052E14',
        'red-50': '#EEF4FF',
        'red-100': '#FFCDD2',
        'red-200': '#EF9A9A',
        'red-300': '#E57373',
        'red-400': '#EF5350',
        'red-500': '#F44336',
        'red-600': '#E53935',
        'red-700': '#D32F2F',
        'red-800': '#C62828',
        'red-900': '#B71C1C',
        'red-950': '#8E0000',
        'yellow-800': '#FFD001',
        black: '#121219',
        white: '#ffffff',
      },
      fontFamily: {
        sans: ['Open Sans', 'sans-serif'],
        varela: ['Varela Round', 'sans-serif'],
        inter: ['Inter', 'sans-serif'],
      },
      keyframes: {
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        'fade-out': {
          '0%': { opacity: '1' },
          '100%': { opacity: '0' },
        },
        'slide-in-right': {
          '0%': { transform: 'translateX(100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-in-left': {
          '0%': { transform: 'translateX(-100%)', opacity: '0' },
          '100%': { transform: 'translateX(0)', opacity: '1' },
        },
        'slide-in-up': {
          '0%': { transform: 'translateY(100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-in-down': {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '100%': { transform: 'translateY(0)', opacity: '1' },
        },
        'slide-out-right': {
          '0%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(100%)', opacity: '0' },
        },
        'slide-out-left': {
          '0%': { transform: 'translateX(0)', opacity: '1' },
          '100%': { transform: 'translateX(-100%)', opacity: '0' },
        },
        'scale-in': {
          '0%': { transform: 'scale(0.9)', opacity: '0' },
          '100%': { transform: 'scale(1)', opacity: '1' },
        },
        'scale-out': {
          '0%': { transform: 'scale(1)', opacity: '1' },
          '100%': { transform: 'scale(0.9)', opacity: '0' },
        },
        'pulse-slow': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '0.5' },
        },
        'bounce-slow': {
          '0%, 100%': {
            transform: 'translateY(0)',
            animationTimingFunction: 'cubic-bezier(0.8, 0, 1, 1)',
          },
          '50%': {
            transform: 'translateY(-25%)',
            animationTimingFunction: 'cubic-bezier(0, 0, 0.2, 1)',
          },
        },
        'shimmer': {
          '0%': { backgroundPosition: '-1000px 0' },
          '100%': { backgroundPosition: '1000px 0' },
        },
        'wiggle': {
          '0%, 100%': { transform: 'rotate(-3deg)' },
          '50%': { transform: 'rotate(3deg)' },
        },
        'float': {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-10px)' },
        },
        'glow': {
          '0%, 100%': { boxShadow: '0 0 5px rgba(0, 82, 205, 0.5)' },
          '50%': { boxShadow: '0 0 20px rgba(0, 82, 205, 0.8)' },
        },
      },
      animation: {
        'fade-in': 'fade-in 0.3s ease-in-out',
        'fade-out': 'fade-out 0.3s ease-in-out',
        'slide-in-right': 'slide-in-right 0.3s ease-out',
        'slide-in-left': 'slide-in-left 0.3s ease-out',
        'slide-in-up': 'slide-in-up 0.3s ease-out',
        'slide-in-down': 'slide-in-down 0.3s ease-out',
        'slide-out-right': 'slide-out-right 0.3s ease-in',
        'slide-out-left': 'slide-out-left 0.3s ease-in',
        'scale-in': 'scale-in 0.2s ease-out',
        'scale-out': 'scale-out 0.2s ease-in',
        'pulse-slow': 'pulse-slow 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'bounce-slow': 'bounce-slow 2s infinite',
        'shimmer': 'shimmer 2s linear infinite',
        'wiggle': 'wiggle 0.5s ease-in-out infinite',
        'float': 'float 3s ease-in-out infinite',
        'glow': 'glow 2s ease-in-out infinite',
      },
    },
  },
  plugins: [],
  darkMode: 'class',
};

